### ISSUE TITLE
Optimize Knowledge Base Navigation

### ISSUE THREAD

**Issue by xanathon** [bussardrobbie/DDL-KB-Kanban#34]
The Navigation in the subsection is not the least user friendly and at the moment completely useless. 
Subnav points are not shown to the left in the vertical menu.
If I click on "Managing Multiple Vectors on Escape Pod" in the navigation to the left the nav point "Developer Tools" is marked bold, even if the user is not on that point in the documentation. An "active" link should indicate a page the user is on at the moment. This is basic html/UX knowledge that is freely available.

Aside from that the Escape Pod documentation is highly unorganized (as is the rest of Vector documentation), it looks as if the person doing the documentation has either no idea how to present a user friendly and clearly organized documentation, or the software used is not able to provide this. Or both.

As I suggested a year ago: Use a Wiki (Mediawiki, Dokuwiki) or at least a industry-proven knowledgebase software instead of that unusable and unprofessional tinker-solution. If this actually is helpscout, as the page source suggests, it was implemented wrong.

**Comment by bussardrobbie** [comment]
Was investigating this. One limiting factor is that the HelpScout platform, while having super easily modifiable content and very convenient to use interfaces, has a limited amount of granularity. I can't, for instance, create subcategories inside categories for users to really drill down into specific topics. The only available options, structurally, are:
-Site
--Collection
---Category
----Article (Can be in multiple categories)

I have discussed with HelpScout my use case and requests for further granularity. Until that change occurs, it may be down to creating alternative Site-level items for each product, with their own subdomains, and then mapping those subdomains to easier-to-use URLs such as "ddl.io/vector/support" and "ddl.io/cozmo/support" or similar.

The current solution is:
-Site (DDL Knowledge Base)
--Collection: Cozmo
---Technical Troubleshooting
--Collection: Vector
---Category: Setup
---Category: SDK
---Category: Technical Troubleshooting (etc.)
---Category: Frequently Asked Questions
--Collection: Cozmo
---Category: Setup
---Category: Features & Usage
---Category: Technical Troubleshooting
etc.


The proposed solution would be, in HelpScout:
-Site 1 (Vector)
--Collection: Vector
---Category: Setup
---Category: SDK
---Category: Technical Troubleshooting (etc.)
--Collection: OSKR
---Category: Installation
---Category: Open Source Repo List
---Category: Maintenance Tasks (etc.)
--Collection: Escape Pod
---Category: Setup
---Category: Technical Troubleshooting
---Category: Tips and Tricks (etc.)
-Site 2 (Cozmo)
--Collection: Cozmo
---Category: Setup
---Category: Features & Usage
---Category: Technical Troubleshooting
--Collection: SDK
---Category: Setup
---Category: Usage
---Category: Examples
-Site 3 (OverDrive)
--etc
-Site 4 (Puzzlets)
--etc

The proposed solution would be beneficial by offering a bit more granularity but more importantly people would only see information regarding the product they actually own and care about, which certainly improves the ability to find information and reduces clutter.

There is a bit of effort in standing up staging areas to complete the full reorganization of the documentation. HelpScout does not offer the ability to duplicate a Site. Instead, they requested that I utilize their API to loop through all of the existing articles and duplicate them on a per-site basis, so that may add to the timeline to complete this reorganization if I choose to go that route.

I am also testing Grav CMS to see if it offers the granularity we need for this use case. I'm early into my testing. I like it so far for basic usage and standup/maintenance.

**Comment by bussardrobbie** [comment]
For the moment, I've restructured the Vector information (Cozmo, OverDrive, etc. are work-in-progress) to be more user friendly with more categories according to the information contained within. Should be more granular- and more helpful.

https://support.digitaldreamlabs.com/collection/6-vector

Feedback welcome.

**Comment by bussardrobbie** [comment]
Cozmo categories are restructured to be significantly more intuitive and allow information to be found faster and more efficiently:
https://support.digitaldreamlabs.com/collection/9-cozmo

**Comment by bussardrobbie** [comment]
Adjusted category names on Escape Pod.

Introduced newer, more clear categories on OverDrive and restructured documentation on a per-app / per-product basis.
